from __future__ import annotations

from pathlib import Path

import pytest

from woon_core.context.compiler import (
    GENERATED_HEADER,
    Compiler,
    audit_directory_names,
    audit_paths,
)
from woon_core.errors import WoonError
from woon_core.registry import Registry, Repository

MAC_USER_HOME = "/" + "Users/example/project"
WINDOWS_USER_HOME = "C:\\" + "Users\\example\\project"


def write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def fixture(tmp_path: Path) -> tuple[Compiler, Path]:
    core = tmp_path / "woon-core"
    target = tmp_path / "target"
    write(core / "config/budgets.yaml", "repository_instruction_bytes: 6144\n")
    write(core / "policies/safety.yaml", "id: safety\nrules: [verify]\n")
    write(core / "standards/code.yaml", "id: code\nrules: [clear]\n")
    write(
        target / ".woon/repository.yaml",
        "id: target\nprofiles: [core]\nrequired_policies: [safety]\n"
        "required_standards: [code]\nrequired_checks: [unit]\n",
    )
    registry = Registry(
        version=1,
        repositories={
            "core": Repository("https://github.com/example/core.git", "woon-core"),
            "target": Repository("https://github.com/example/target.git", "target"),
            "output": Repository("https://github.com/example/output.git", "output", output=True),
        },
    )
    return Compiler(tmp_path, registry), target


def test_generate_then_check_is_deterministic(tmp_path: Path) -> None:
    compiler, target = fixture(tmp_path)
    first = compiler.generate(False, ["target"])
    assert first.artifacts == 3
    before = (target / "AGENTS.md").read_bytes()
    compiler.generate(False, ["target"])
    assert (target / "AGENTS.md").read_bytes() == before
    assert compiler.check(False, ["target"]).artifacts == 3
    assert not (target / ".cursor").exists()


def test_generate_refuses_unmanaged_instruction(tmp_path: Path) -> None:
    compiler, target = fixture(tmp_path)
    write(target / "AGENTS.md", "human-owned\n")
    with pytest.raises(WoonError, match="unmanaged"):
        compiler.generate(False, ["target"])


def test_select_ids_excludes_output_repositories(tmp_path: Path) -> None:
    compiler, _ = fixture(tmp_path)
    assert compiler._select_ids(True, []) == ["core", "target"]
    with pytest.raises(WoonError, match="output-only"):
        compiler._select_ids(False, ["output"])


@pytest.mark.parametrize("content", [f"path: {MAC_USER_HOME}\n", f"path: {WINDOWS_USER_HOME}\n"])
def test_audit_paths_rejects_user_homes(tmp_path: Path, content: str) -> None:
    write(tmp_path / "config.yaml", content)
    with pytest.raises(WoonError, match="absolute user paths"):
        audit_paths(tmp_path, [], [])


def test_audit_paths_ignores_local_and_generated_files(tmp_path: Path) -> None:
    write(tmp_path / ".local/receipt.json", f'"{MAC_USER_HOME}"')
    write(tmp_path / "generated/result.json", f'"{MAC_USER_HOME}"')
    audit_paths(tmp_path, ["generated"], [])


def test_audit_paths_ignores_declared_raw_source_root_only(tmp_path: Path) -> None:
    write(tmp_path / "wiki/private/_sources/raw.json", f'"{MAC_USER_HOME}"')
    write(tmp_path / "config.yaml", "enabled: true\n")

    audit_paths(tmp_path, [], [], ["wiki/private/_sources"])

    write(tmp_path / "config.yaml", f'path: "{MAC_USER_HOME}"\n')
    with pytest.raises(WoonError, match="absolute user paths"):
        audit_paths(tmp_path, [], [], ["wiki/private/_sources"])


def test_audit_paths_allows_regex_detector_but_rejects_runtime_value(tmp_path: Path) -> None:
    write(
        tmp_path / "detector.py",
        'import re\nMACHINE_PATH = re.compile(r"/' + 'Users/|/home/[^/]+")\n',
    )
    audit_paths(tmp_path, [], [])

    write(
        tmp_path / "settings.py",
        'data_directory = "/' + 'Users/example/private"\n',
    )
    with pytest.raises(WoonError, match="absolute user paths"):
        audit_paths(tmp_path, [], [])


def test_generated_header_is_stable() -> None:
    assert GENERATED_HEADER.startswith("<!-- Code generated by woon")


def test_directory_name_audit_accepts_language_conventions(tmp_path: Path) -> None:
    (tmp_path / ".github/workflows").mkdir(parents=True)
    (tmp_path / "src/woon_core").mkdir(parents=True)
    (tmp_path / "src/woon_core/__init__.py").touch()
    (tmp_path / "src/components/project-detail").mkdir(parents=True)
    (tmp_path / "src/main/java/org/example/core").mkdir(parents=True)

    audit_directory_names(tmp_path)


def test_directory_name_audit_ignores_obsidian_tool_owned_directories(tmp_path: Path) -> None:
    (tmp_path / ".obsidian/themes/Minimal").mkdir(parents=True)

    audit_directory_names(tmp_path)


def test_directory_name_audit_ignores_declared_canonical_data_roots(tmp_path: Path) -> None:
    (tmp_path / "wiki/private/novel/사건-히스토리").mkdir(parents=True)
    (tmp_path / "wiki/private/_sources/raw_source").mkdir(parents=True)

    audit_directory_names(tmp_path, ["wiki/private/novel", "wiki/private/_sources"])


def test_directory_name_audit_rejects_spaces_and_uppercase(tmp_path: Path) -> None:
    (tmp_path / "Bad Folder").mkdir()

    with pytest.raises(WoonError, match="non-canonical directory names"):
        audit_directory_names(tmp_path)


def test_directory_name_audit_rejects_underscore_outside_python_package(tmp_path: Path) -> None:
    (tmp_path / "source_vault").mkdir()

    with pytest.raises(WoonError, match="non-canonical directory names"):
        audit_directory_names(tmp_path)


def test_directory_name_audit_rejects_uppercase_java_package(tmp_path: Path) -> None:
    (tmp_path / "src/main/java/org/example/App").mkdir(parents=True)

    with pytest.raises(WoonError, match="non-canonical directory names"):
        audit_directory_names(tmp_path)
