package contextdoc

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"text/template"

	"github.com/woonyong-kr/woon-core/internal/registry"
	"gopkg.in/yaml.v3"
)

const generatedHeader = "<!-- Code generated by woon. DO NOT EDIT. -->"

var absoluteUserPathPatterns = []*regexp.Regexp{
	regexp.MustCompile("/" + `Users/[^/[:space:]]+/`),
	regexp.MustCompile(`[A-Za-z]:\\` + `Users\\[^\\[:space:]]+\\`),
}

type Manifest struct {
	ID                  string               `yaml:"id"`
	Profiles            []string             `yaml:"profiles"`
	RequiredPolicies    []string             `yaml:"required_policies"`
	RequiredStandards   []string             `yaml:"required_standards"`
	RequiredChecks      []string             `yaml:"required_checks"`
	GeneratedPaths      []string             `yaml:"generated_paths,omitempty"`
	PathAuditExceptions []PathAuditException `yaml:"path_audit_exceptions,omitempty"`
}

type PathAuditException struct {
	Path   string `yaml:"path"`
	Reason string `yaml:"reason"`
}

type Policy struct {
	ID    string   `yaml:"id"`
	Rules []string `yaml:"rules"`
}

type Standard struct {
	ID            string   `yaml:"id"`
	Rules         []string `yaml:"rules"`
	RequiredPaths []string `yaml:"required_paths,omitempty"`
}

type Budgets struct {
	GlobalBootstrapBytes int `yaml:"global_bootstrap_bytes"`
	RepositoryBytes      int `yaml:"repository_instruction_bytes"`
}

type Compiler struct {
	root      string
	core      string
	registry  registry.Registry
	policies  map[string]Policy
	standards map[string]Standard
	budgets   Budgets
	tmpl      *template.Template
}

type Result struct {
	Repositories int
	Artifacts    int
}

type templateData struct {
	Header    string
	Target    string
	Manifest  Manifest
	Policies  []Policy
	Standards []Standard
}

var outputTargets = map[string]string{
	"agents":  "AGENTS.md",
	"claude":  "CLAUDE.md",
	"cursor":  ".cursor/rules/woon-generated.mdc",
	"copilot": ".github/copilot-instructions.md",
}

func New(root string, reg registry.Registry) (*Compiler, error) {
	core, err := reg.Resolve(root, "core")
	if err != nil {
		return nil, err
	}
	budgets, err := loadYAML[Budgets](filepath.Join(core, "config", "budgets.yaml"))
	if err != nil {
		return nil, err
	}
	policies, err := loadPolicies(filepath.Join(core, "policies"))
	if err != nil {
		return nil, err
	}
	standards, err := loadStandards(filepath.Join(core, "standards"))
	if err != nil {
		return nil, err
	}
	templateBytes, err := os.ReadFile(filepath.Join(core, "templates", "context", "instruction.md.tmpl"))
	if err != nil {
		return nil, fmt.Errorf("read context template: %w", err)
	}
	tmpl, err := template.New("instruction").Parse(string(templateBytes))
	if err != nil {
		return nil, fmt.Errorf("parse context template: %w", err)
	}
	return &Compiler{root: root, core: core, registry: reg, policies: policies, standards: standards, budgets: budgets, tmpl: tmpl}, nil
}

func (c *Compiler) Generate(all bool, ids []string) (Result, error) {
	selected, err := c.selectIDs(all, ids)
	if err != nil {
		return Result{}, err
	}
	var result Result
	for _, id := range selected {
		repoPath, err := c.registry.Resolve(c.root, id)
		if err != nil {
			return result, err
		}
		if _, err := os.Stat(repoPath); errors.Is(err, os.ErrNotExist) {
			continue
		}
		manifest, err := loadYAML[Manifest](filepath.Join(repoPath, "woon.yaml"))
		if err != nil {
			return result, fmt.Errorf("%s: %w", id, err)
		}
		artifacts, err := c.render(manifest)
		if err != nil {
			return result, fmt.Errorf("%s: %w", id, err)
		}
		for target, data := range artifacts {
			path := filepath.Join(repoPath, filepath.FromSlash(outputTargets[target]))
			if err := atomicWrite(path, data); err != nil {
				return result, err
			}
			result.Artifacts++
		}
		result.Repositories++
	}
	return result, nil
}

func (c *Compiler) Check(all bool, ids []string) (Result, error) {
	selected, err := c.selectIDs(all, ids)
	if err != nil {
		return Result{}, err
	}
	var result Result
	for _, id := range selected {
		repoPath, err := c.registry.Resolve(c.root, id)
		if err != nil {
			return result, err
		}
		if _, err := os.Stat(repoPath); errors.Is(err, os.ErrNotExist) {
			continue
		}
		manifest, err := loadYAML[Manifest](filepath.Join(repoPath, "woon.yaml"))
		if err != nil {
			return result, fmt.Errorf("%s: %w", id, err)
		}
		artifacts, err := c.render(manifest)
		if err != nil {
			return result, fmt.Errorf("%s: %w", id, err)
		}
		for target, expected := range artifacts {
			path := filepath.Join(repoPath, filepath.FromSlash(outputTargets[target]))
			actual, err := os.ReadFile(path)
			if err != nil {
				return result, fmt.Errorf("read generated artifact %s: %w", path, err)
			}
			if !bytes.Equal(actual, expected) {
				return result, fmt.Errorf("generated artifact drift: %s", path)
			}
			result.Artifacts++
		}
		if err := auditPaths(repoPath, manifest.GeneratedPaths, manifest.PathAuditExceptions); err != nil {
			return result, fmt.Errorf("%s: %w", id, err)
		}
		if err := c.checkRequiredPaths(repoPath, manifest); err != nil {
			return result, fmt.Errorf("%s: %w", id, err)
		}
		result.Repositories++
	}
	return result, nil
}

func (c *Compiler) render(manifest Manifest) (map[string][]byte, error) {
	if manifest.ID == "" {
		return nil, errors.New("woon.yaml requires id")
	}
	var policies []Policy
	for _, id := range manifest.RequiredPolicies {
		policy, ok := c.policies[id]
		if !ok {
			return nil, fmt.Errorf("unknown required policy %q", id)
		}
		policies = append(policies, policy)
	}
	sort.Slice(policies, func(i, j int) bool { return policies[i].ID < policies[j].ID })
	var standards []Standard
	for _, id := range manifest.RequiredStandards {
		standard, ok := c.standards[id]
		if !ok {
			return nil, fmt.Errorf("unknown required standard %q", id)
		}
		standards = append(standards, standard)
	}
	sort.Slice(standards, func(i, j int) bool { return standards[i].ID < standards[j].ID })
	result := make(map[string][]byte, len(outputTargets))
	for target := range outputTargets {
		var buffer bytes.Buffer
		data := templateData{Header: generatedHeader, Target: target, Manifest: manifest, Policies: policies, Standards: standards}
		if err := c.tmpl.Execute(&buffer, data); err != nil {
			return nil, err
		}
		bytes := buffer.Bytes()
		budget := c.budgets.RepositoryBytes
		if len(bytes) > budget {
			return nil, fmt.Errorf("%s instructions exceed %d-byte budget: %d", target, budget, len(bytes))
		}
		result[target] = bytes
	}
	return result, nil
}

func (c *Compiler) checkRequiredPaths(repoPath string, manifest Manifest) error {
	for _, id := range manifest.RequiredStandards {
		standard := c.standards[id]
		for _, required := range standard.RequiredPaths {
			if filepath.IsAbs(required) || strings.Contains(filepath.ToSlash(required), "../") {
				return fmt.Errorf("standard %q has unsafe required path %q", id, required)
			}
			if _, err := os.Stat(filepath.Join(repoPath, filepath.FromSlash(required))); err != nil {
				return fmt.Errorf("required path missing: %s", required)
			}
		}
	}
	return nil
}

func (c *Compiler) selectIDs(all bool, ids []string) ([]string, error) {
	if all {
		ids = ids[:0]
		for id := range c.registry.Repositories {
			ids = append(ids, id)
		}
	}
	seen := map[string]bool{}
	selected := make([]string, 0, len(ids))
	for _, id := range ids {
		if _, ok := c.registry.Repositories[id]; !ok {
			return nil, fmt.Errorf("unknown repository %q", id)
		}
		if !seen[id] {
			selected = append(selected, id)
			seen[id] = true
		}
	}
	sort.Strings(selected)
	return selected, nil
}

func loadPolicies(dir string) (map[string]Policy, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, fmt.Errorf("read policies: %w", err)
	}
	result := map[string]Policy{}
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".yaml") {
			continue
		}
		policy, err := loadYAML[Policy](filepath.Join(dir, entry.Name()))
		if err != nil {
			return nil, err
		}
		if policy.ID == "" || len(policy.Rules) == 0 {
			return nil, fmt.Errorf("invalid policy %s", entry.Name())
		}
		if _, exists := result[policy.ID]; exists {
			return nil, fmt.Errorf("duplicate policy %q", policy.ID)
		}
		result[policy.ID] = policy
	}
	return result, nil
}

func loadStandards(dir string) (map[string]Standard, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, fmt.Errorf("read standards: %w", err)
	}
	result := map[string]Standard{}
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".yaml") {
			continue
		}
		standard, err := loadYAML[Standard](filepath.Join(dir, entry.Name()))
		if err != nil {
			return nil, err
		}
		if standard.ID == "" || len(standard.Rules) == 0 {
			return nil, fmt.Errorf("invalid standard %s", entry.Name())
		}
		if _, exists := result[standard.ID]; exists {
			return nil, fmt.Errorf("duplicate standard %q", standard.ID)
		}
		result[standard.ID] = standard
	}
	return result, nil
}

func loadYAML[T any](path string) (T, error) {
	var value T
	data, err := os.ReadFile(path)
	if err != nil {
		return value, fmt.Errorf("read %s: %w", path, err)
	}
	decoder := yaml.NewDecoder(bytes.NewReader(data))
	decoder.KnownFields(true)
	if err := decoder.Decode(&value); err != nil {
		return value, fmt.Errorf("parse %s: %w", path, err)
	}
	return value, nil
}

func auditPaths(root string, generatedPaths []string, exceptions []PathAuditException) error {
	generated := map[string]bool{}
	for _, generatedPath := range generatedPaths {
		clean := filepath.Clean(filepath.FromSlash(generatedPath))
		if generatedPath == "" || filepath.IsAbs(clean) || clean == "." || clean == ".." || strings.HasPrefix(clean, ".."+string(filepath.Separator)) {
			return fmt.Errorf("invalid generated path %q", generatedPath)
		}
		generated[filepath.ToSlash(clean)] = true
	}
	excluded := map[string]bool{}
	for _, exception := range exceptions {
		clean := filepath.Clean(filepath.FromSlash(exception.Path))
		if exception.Path == "" || exception.Reason == "" || filepath.IsAbs(clean) || clean == "." || clean == ".." || strings.HasPrefix(clean, ".."+string(filepath.Separator)) {
			return fmt.Errorf("invalid path audit exception %q", exception.Path)
		}
		info, err := os.Stat(filepath.Join(root, clean))
		if err != nil {
			return fmt.Errorf("path audit exception %q: %w", exception.Path, err)
		}
		if info.IsDir() {
			return fmt.Errorf("path audit exception must be a file: %q", exception.Path)
		}
		excluded[filepath.ToSlash(clean)] = true
	}
	var violations []string
	err := filepath.WalkDir(root, func(path string, entry os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		relative, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		relative = filepath.ToSlash(relative)
		if generated[relative] {
			if entry.IsDir() {
				return filepath.SkipDir
			}
			return nil
		}
		if entry.IsDir() {
			name := entry.Name()
			if name == ".git" || name == "node_modules" || name == "vendor" || name == "generated" || name == "_archive" || name == "_to_delete" || name == ".legacy-backup" {
				return filepath.SkipDir
			}
			return nil
		}
		if !isOperational(root, path) {
			return nil
		}
		if excluded[relative] {
			return nil
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		for _, pattern := range absoluteUserPathPatterns {
			if pattern.Match(data) {
				violations = append(violations, relative)
				break
			}
		}
		return nil
	})
	if err != nil {
		return err
	}
	if len(violations) != 0 {
		sort.Strings(violations)
		return fmt.Errorf("absolute user paths found in operational files: %s", strings.Join(violations, ", "))
	}
	return nil
}

func isOperational(root, path string) bool {
	ext := strings.ToLower(filepath.Ext(path))
	switch ext {
	case ".go", ".py", ".sh", ".ps1", ".yaml", ".yml", ".json", ".toml", ".xml", ".tmpl":
		return true
	case ".md":
		relative, err := filepath.Rel(root, path)
		if err != nil {
			return true
		}
		relative = filepath.ToSlash(relative)
		base := filepath.Base(path)
		return relative == "README.md" || base == "AGENTS.md" || base == "CLAUDE.md" ||
			strings.HasPrefix(relative, ".claude/") || strings.HasPrefix(relative, ".cursor/") ||
			strings.HasPrefix(relative, ".github/") || strings.HasPrefix(relative, "docs/")
	default:
		return false
	}
}

func atomicWrite(path string, data []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	if existing, err := os.ReadFile(path); err == nil && !bytes.HasPrefix(existing, []byte(generatedHeader)) {
		return fmt.Errorf("refusing to overwrite unmanaged file %s", path)
	}
	tmp, err := os.CreateTemp(filepath.Dir(path), ".woon-context-*")
	if err != nil {
		return err
	}
	tmpPath := tmp.Name()
	defer os.Remove(tmpPath)
	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	if err := os.Rename(tmpPath, path); err != nil {
		return err
	}
	return nil
}
