"""Compile repository policies into deterministic agent instructions."""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path, PurePosixPath
from typing import Any

from woon_core.errors import WoonError
from woon_core.io import atomic_write, load_yaml
from woon_core.registry import Registry

GENERATED_HEADER = "<!-- Code generated by woon. DO NOT EDIT. -->"
REPOSITORY_MANIFEST = Path(".woon/repository.yaml")
OUTPUT_TARGETS = {
    "agents": Path("AGENTS.md"),
    "claude": Path("CLAUDE.md"),
    "copilot": Path(".github/copilot-instructions.md"),
}
ABSOLUTE_USER_PATH_PATTERNS = (
    re.compile(b"/" + rb"Users/[^/\s]+/"),
    re.compile(rb"[A-Za-z]:\\Users\\[^\\\s]+\\"),
)
GENERIC_DIRECTORY_NAME = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
PYTHON_PACKAGE_NAME = re.compile(r"^[a-z][a-z0-9]*(?:_[a-z0-9]+)*$")
JAVA_PACKAGE_NAME = re.compile(r"^[a-z][a-z0-9]*$")
SKIPPED_DIRECTORIES = {
    ".git",
    ".local",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    "node_modules",
    "vendor",
    "generated",
    "_archive",
    "_to_delete",
    ".legacy-backup",
    ".venv",
    "__pycache__",
    "dist",
}


@dataclass(frozen=True, slots=True)
class CompileResult:
    repositories: int
    artifacts: int


class Compiler:
    def __init__(self, root: Path, registry: Registry) -> None:
        self.root = root
        self.registry = registry
        self.core = registry.resolve(root, "core")
        budget = load_yaml(self.core / "config/budgets.yaml").get("repository_instruction_bytes")
        if not isinstance(budget, int) or budget <= 0:
            raise WoonError("repository_instruction_bytes must be a positive integer")
        self.repository_budget = budget
        self.policies = self._load_rules(self.core / "policies", "policy")
        self.standards = self._load_rules(self.core / "standards", "standard")

    def generate(self, all_repositories: bool, identifiers: list[str]) -> CompileResult:
        repositories = 0
        artifacts_count = 0
        for identifier in self._select_ids(all_repositories, identifiers):
            repository_path = self.registry.resolve(self.root, identifier)
            if not repository_path.exists():
                continue
            manifest = load_yaml(repository_path / REPOSITORY_MANIFEST)
            artifacts = self._render(manifest)
            for target, data in artifacts.items():
                path = repository_path / OUTPUT_TARGETS[target]
                if path.exists() and not path.read_bytes().startswith(GENERATED_HEADER.encode()):
                    raise WoonError(f"refusing to overwrite unmanaged file {path}")
                atomic_write(path, data)
                artifacts_count += 1
            repositories += 1
        return CompileResult(repositories=repositories, artifacts=artifacts_count)

    def check(self, all_repositories: bool, identifiers: list[str]) -> CompileResult:
        repositories = 0
        artifacts_count = 0
        for identifier in self._select_ids(all_repositories, identifiers):
            repository_path = self.registry.resolve(self.root, identifier)
            if not repository_path.exists():
                continue
            manifest = load_yaml(repository_path / REPOSITORY_MANIFEST)
            artifacts = self._render(manifest)
            for target, expected in artifacts.items():
                path = repository_path / OUTPUT_TARGETS[target]
                try:
                    actual = path.read_bytes()
                except OSError as error:
                    raise WoonError(f"read generated artifact {path}: {error}") from error
                if actual != expected:
                    raise WoonError(f"generated artifact drift: {path}")
                artifacts_count += 1
            audit_paths(
                repository_path,
                _string_list(manifest.get("generated_paths", []), "generated_paths"),
                manifest.get("path_audit_exceptions", []),
            )
            audit_directory_names(repository_path)
            self._check_required_paths(repository_path, manifest)
            repositories += 1
        return CompileResult(repositories=repositories, artifacts=artifacts_count)

    def _render(self, manifest: dict[str, Any]) -> dict[str, bytes]:
        identifier = manifest.get("id")
        if not isinstance(identifier, str) or not identifier:
            raise WoonError(".woon/repository.yaml requires id")
        profiles = _string_list(manifest.get("profiles", []), "profiles")
        required_policies = _string_list(manifest.get("required_policies", []), "required_policies")
        required_standards = _string_list(
            manifest.get("required_standards", []), "required_standards"
        )
        checks = _string_list(manifest.get("required_checks", []), "required_checks")
        if not checks:
            raise WoonError(".woon/repository.yaml requires required_checks")

        policies = self._select_rules(required_policies, self.policies, "policy")
        standards = self._select_rules(required_standards, self.standards, "standard")
        artifacts: dict[str, bytes] = {}
        for target in OUTPUT_TARGETS:
            lines = [
                GENERATED_HEADER,
                f"# Woon 지침: {identifier}",
                "",
                f"대상: `{target}`",
                "Profiles: " + ", ".join(f"`{profile}`" for profile in profiles),
                "",
                "## 필수 작업 순서",
                "",
                "1. `.woon/repository.yaml`을 읽고 교차 저장소 링크는 `woon resolve`로 해석한다.",
                "2. 관련 없는 변경을 보존하고 정본 파일만 편집한다.",
                "3. `required_checks`에 선언된 검증을 실행한다.",
                "4. 생성 파일을 직접 편집하지 않고 정본에서 다시 생성한다.",
                "5. 검증을 통과하기 전에는 완료로 보고하지 않는다.",
            ]
            for rule_identifier, rules in policies:
                lines.extend(("", f"## 정책: {rule_identifier}"))
                lines.extend(f"- {rule}" for rule in rules)
            for rule_identifier, rules in standards:
                lines.extend(("", f"## 표준: {rule_identifier}"))
                lines.extend(f"- {rule}" for rule in rules)
            data = ("\n".join(lines) + "\n").encode()
            if len(data) > self.repository_budget:
                raise WoonError(
                    f"{target} instructions exceed {self.repository_budget}-byte budget: "
                    f"{len(data)}"
                )
            artifacts[target] = data
        return artifacts

    def _select_rules(
        self,
        identifiers: list[str],
        available: dict[str, list[str]],
        kind: str,
    ) -> tuple[tuple[str, list[str]], ...]:
        selected: list[tuple[str, list[str]]] = []
        for identifier in identifiers:
            try:
                selected.append((identifier, available[identifier]))
            except KeyError as error:
                raise WoonError(f"unknown required {kind} {identifier!r}") from error
        return tuple(sorted(selected))

    def _select_ids(self, all_repositories: bool, identifiers: list[str]) -> list[str]:
        selected = (
            [
                identifier
                for identifier, repository in self.registry.repositories.items()
                if not repository.output
            ]
            if all_repositories
            else identifiers
        )
        unique: set[str] = set()
        for identifier in selected:
            try:
                repository = self.registry.repositories[identifier]
            except KeyError as error:
                raise WoonError(f"unknown repository {identifier!r}") from error
            if repository.output:
                raise WoonError(
                    f"repository {identifier!r} is output-only and has no generated context"
                )
            unique.add(identifier)
        return sorted(unique)

    def _check_required_paths(self, repository_path: Path, manifest: dict[str, Any]) -> None:
        for identifier in _string_list(
            manifest.get("required_standards", []), "required_standards"
        ):
            standard = load_yaml(self.core / "standards" / f"{identifier}.yaml")
            for raw_path in _string_list(standard.get("required_paths", []), "required_paths"):
                relative = _safe_relative(raw_path, "required path")
                if not (repository_path / relative).exists():
                    raise WoonError(f"required path missing: {raw_path}")

    @staticmethod
    def _load_rules(directory: Path, kind: str) -> dict[str, list[str]]:
        loaded: dict[str, list[str]] = {}
        for path in sorted(directory.glob("*.yaml")):
            value = load_yaml(path)
            identifier = value.get("id")
            rules = _string_list(value.get("rules", []), "rules")
            if not isinstance(identifier, str) or not identifier or not rules:
                raise WoonError(f"invalid {kind} {path.name}")
            if identifier in loaded:
                raise WoonError(f"duplicate {kind} {identifier!r}")
            loaded[identifier] = rules
        return loaded


def audit_paths(root: Path, generated_paths: list[str], raw_exceptions: object) -> None:
    generated = {_safe_relative(value, "generated path") for value in generated_paths}
    if not isinstance(raw_exceptions, list):
        raise WoonError("path_audit_exceptions must be a list")
    excluded: set[Path] = set()
    for item in raw_exceptions:
        if not isinstance(item, dict):
            raise WoonError("path audit exception must be a mapping")
        raw_path = item.get("path")
        reason = item.get("reason")
        if not isinstance(raw_path, str) or not isinstance(reason, str) or not reason:
            raise WoonError("path audit exception requires path and reason")
        relative = _safe_relative(raw_path, "path audit exception")
        path = root / relative
        if not path.is_file():
            raise WoonError(f"path audit exception must be a file: {raw_path!r}")
        excluded.add(relative)

    violations: list[str] = []
    for path in sorted(root.rglob("*")):
        relative = path.relative_to(root)
        if any(part in SKIPPED_DIRECTORIES for part in relative.parts):
            continue
        if any(relative == item or item in relative.parents for item in generated):
            continue
        if not path.is_file() or relative in excluded or not _is_operational(relative):
            continue
        data = path.read_bytes()
        if any(pattern.search(data) for pattern in ABSOLUTE_USER_PATH_PATTERNS):
            violations.append(relative.as_posix())
    if violations:
        raise WoonError("absolute user paths found in operational files: " + ", ".join(violations))


def audit_directory_names(root: Path) -> None:
    """Enforce kebab-case except for language and tool owned directories."""

    violations: list[str] = []
    for path in sorted(item for item in root.rglob("*") if item.is_dir()):
        relative = path.relative_to(root)
        if any(part in SKIPPED_DIRECTORIES for part in relative.parts):
            continue
        name = path.name
        if name.startswith((".", "_")):
            continue
        files = tuple(item for item in path.rglob("*") if item.is_file())
        if files and all(item.suffix == ".pyc" for item in files):
            continue
        if _is_python_package(path, root):
            valid = PYTHON_PACKAGE_NAME.fullmatch(name) is not None
        elif _is_java_package(path, root):
            valid = JAVA_PACKAGE_NAME.fullmatch(name) is not None
        else:
            valid = GENERIC_DIRECTORY_NAME.fullmatch(name) is not None
        if not valid:
            violations.append(relative.as_posix())
    if violations:
        raise WoonError("non-canonical directory names: " + ", ".join(violations))


def _is_python_package(path: Path, root: Path) -> bool:
    for parent in (path, *path.parents):
        if parent == root:
            return False
        if (parent / "__init__.py").is_file():
            return True
    return False


def _is_java_package(path: Path, root: Path) -> bool:
    parts = path.relative_to(root).parts
    return any(
        parts[index : index + 3] in {("src", "main", "java"), ("src", "test", "java")}
        for index in range(max(0, len(parts) - 2))
    )


def _is_operational(relative: Path) -> bool:
    if relative.suffix.lower() in {
        ".go",
        ".py",
        ".sh",
        ".ps1",
        ".yaml",
        ".yml",
        ".json",
        ".toml",
        ".xml",
        ".tmpl",
    }:
        return True
    if relative.suffix.lower() != ".md":
        return False
    return (
        relative == Path("README.md")
        or relative.name in {"AGENTS.md", "CLAUDE.md"}
        or relative.parts[0] in {".claude", ".github", "docs"}
    )


def _safe_relative(value: str, description: str) -> Path:
    path = PurePosixPath(value)
    if not value or path.is_absolute() or path in {PurePosixPath("."), PurePosixPath("..")}:
        raise WoonError(f"invalid {description} {value!r}")
    if ".." in path.parts:
        raise WoonError(f"invalid {description} {value!r}")
    return Path(*path.parts)


def _string_list(value: object, name: str) -> list[str]:
    if not isinstance(value, list) or any(not isinstance(item, str) for item in value):
        raise WoonError(f"{name} must be a list of strings")
    return list(value)
